# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/help_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(551, 447)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/resources/icon/帮助.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Frame.setWindowIcon(icon)
        Frame.setStyleSheet("QTextBrowser#textBrowser{\n"
" background-color: rgba(0,0,0,0);\n"
" selection-background-color:#88bbff;\n"
" border: 0px solid rgba(0,0,0,0);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(Frame)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "帮助"))
        self.textBrowser.setHtml(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt; font-weight:600;\">系统安装</span><span style=\" font-size:11pt; font-weight:600;\"> </span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">双击</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\">speech_enhancement-Setup.exe</span><span style=\" font-family:\'宋体\'; font-size:11pt;\">程序进行软件的安装</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/bz/bz/1.png\" width=\"200\" height=\"200\" /><img src=\":/bz/bz/2.png\" width=\"200\" height=\"200\" /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\"> </span><span style=\" font-family:\'宋体\'; font-size:11pt;\">安装软件许可协议</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/bz/bz/3.png\" width=\"200\" height=\"200\" /><img src=\":/bz/bz/4.png\" width=\"200\" height=\"200\" /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">选择安装的路径</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/bz/bz/5.png\" width=\"200\" height=\"200\" /><img src=\":/bz/bz/6.png\" width=\"200\" height=\"200\" /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">进行安装</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt; font-weight:600;\">程序启动</span><span style=\" font-size:11pt; font-weight:600;\"> </span></h3>\n"
"<h3 align=\"center\" style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/bz/bz/7.png\" width=\"200\" height=\"200\" /></h3>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">程序启动界面</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\"> </span><span style=\" font-size:11pt;\"> </span></p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt; font-weight:600;\">用户注册</span><span style=\" font-size:11pt; font-weight:600;\"> </span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">如果用户名称重复，会提示用户名重复，如果密码两次输入不一样，会提示重新输入。</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/bz/bz/8.png\" width=\"200\" height=\"200\" /><img src=\":/bz/bz/9.png\" width=\"200\" height=\"200\" /><a name=\"图片_x0020_18\"></a><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\"> </span><a name=\"图片_x0020_23\"></a><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\"> </span><span style=\" font-family:\'宋体\'; font-size:11pt;\">用户注册失败界面</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/bz/bz/10.png\" width=\"200\" height=\"200\" /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\"> </span><span style=\" font-family:\'宋体\'; font-size:11pt;\">用户注册成功界面</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\"> </span><span style=\" font-size:11pt;\"> </span></p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt; font-weight:600;\">用户登录</span><span style=\" font-size:11pt; font-weight:600;\"> </span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">登录成功会显示用户的名称以及在数据库中的用户字段</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/bz/bz/11.png\" width=\"200\" height=\"200\" /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\"> </span><span style=\" font-family:\'宋体\'; font-size:11pt;\">用户登录成功界面</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">如果用户名密码输入错误，提示登录失败，可以点击下面的忘记密码，联系管理员，进行密码的修改</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"图片_x0020_11\"></a><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\"> </span><a name=\"图片_x0020_27\"></a><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/bz/bz/12.png\" width=\"200\" height=\"200\" /><img src=\":/bz/bz/13.png\" width=\"200\" height=\"200\" /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">用户登录失败界面</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt; font-weight:600;\">管理员登录账户管理</span><span style=\" font-size:11pt; font-weight:600;\"> </span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">点击登录界面左上角的数据库进行登录，如果下面的界面管理员没有的登陆，则不能使用和查看相关功能，需要管理员在左上角进行登录</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/bz/bz/14.png\" width=\"200\" height=\"200\" /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">管理员未登录界面</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">管理员登录成功，可以对用户表进行增删改查的操作。展示密码并不是明文存储的，是经过</span><span style=\" font-size:11pt;\">md5</span><span style=\" font-family:\'宋体\'; font-size:11pt;\">加密以后的，即使是管理员也不能知道密码，因此需要管理员必须重新设置用户的密码。这里有用户的创建时间以及用户的其他相关信息，并不是在数据库中这样存储的，是经过格式化之后的图表。每次操作后，会刷新旁边的用户表。</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/bz/bz/15.png\" width=\"200\" height=\"200\" /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\"> </span><span style=\" font-family:\'宋体\'; font-size:11pt;\">管理员界面</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt; font-weight:600;\">语音增强</span><span style=\" font-size:11pt; font-weight:600;\"> </span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">用户登录成功以后进入语音增强的界面，在这个界面中，用户可以选择需要增强的语音，以及保存的路径。默认的模型文件是通过开源数据集进行训练的，都是英文语境下的数据，增强的效果和数据集有关，后期如果有中文的数据集可以进行训练，得到的模型文件能够直接替换掉现在的模型文件。</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/bz/bz/16.png\" width=\"200\" height=\"200\" /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">语音增强界面</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\"> 1</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/bz/bz/17.png\" width=\"200\" height=\"200\" /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">语音增强界面</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\"> 2</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">语音增强结束可以点击更新增强结束的数据，查看两者的语音频谱图，也可以点击播放原始文件以及播放语音增强后的文件，来感受增强前后的区别。</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/bz/bz/18.png\" width=\"200\" height=\"200\" /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">语音增强界面</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\"> 3</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt; font-weight:600;\">语音增强对比实验</span><span style=\" font-size:11pt; font-weight:600;\"> </span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">选择模型为。维纳滤波，可以看到只有两个选项，并不需要选择模型文件，这是因为维拉滤波是根据前面几秒的环境噪音，来消除后面出现的环境噪音，是经过数学方法对声音进行傅里叶变换处理的，可以点击播放原始文件以及播放语音增强后的文件。</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/bz/bz/19.png\" width=\"200\" height=\"200\" /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">语音增强界面</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\"> 4</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt; font-weight:600;\">录音功能</span><span style=\" font-size:11pt; font-weight:600;\"> </span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">点击左侧的麦克风图标，就可以进入录音的界面，可以选择保存的位置，默认是保存在桌面的。</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/bz/bz/20.png\" width=\"200\" height=\"200\" /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\"> </span><span style=\" font-family:\'宋体\'; font-size:11pt;\">录音界面</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt; font-weight:600;\">软件信息</span><span style=\" font-size:11pt; font-weight:600;\"> </span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">点击左侧的信息图标，可以显示软件的信息，后期有更新的话，可以通过这个界面查看更新的信息，以及跳转到更新的网页下载最新的安装包，这里显示网络失败是因为还未答辩结束，这个项目暂未开源到</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\">GitHub</span><span style=\" font-family:\'宋体\'; font-size:11pt;\">上，因此连接不上最新的项目地址。</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/bz/bz/21.png\" width=\"200\" height=\"200\" /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\"> </span><span style=\" font-family:\'宋体\'; font-size:11pt;\">软件信息界面</span><span style=\" font-size:11pt;\"> </span></p></body></html>"))
from res import app_rc
