# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/探测声音.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QPushButton#main_pushButton,#sound_recording_pushButton,#about_pushButton,#help_pushButton{\n"
"background-color: rgb(255, 117, 194);\n"
"border:rgb(255, 117, 194);\n"
"border-radius: 14;\n"
"}\n"
"\n"
"QPushButton#main_pushButton:hover,#sound_recording_pushButton:hover,#about_pushButton:hover,#help_pushButton:hover{\n"
"background-color: rgba(255, 117, 194,200);\n"
"}\n"
"\n"
"QPushButton#main_pushButton:pressed,#sound_recording_pushButton:pressed,#about_pushButton:pressed,#help_pushButton:pressed{\n"
"background-color: rgb(170, 88, 117);\n"
"}\n"
"\n"
"QPushButton#close_pushButton{\n"
" background-color: #ce5137;\n"
" border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#close_pushButton:hover{\n"
" background-size: cover;\n"
" background-image: url(:/icon/icon/close.svg);\n"
"}\n"
"\n"
"QPushButton#min_pushButton{\n"
" background-color: #a1c661;\n"
" border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#min_pushButton:hover{\n"
" background-size: cover;\n"
" background-image: url(:/icon/icon/minimize.svg);\n"
"}\n"
"\n"
"\n"
"QWidget#button_widget{\n"
"background-color: rgb(62, 32,110);\n"
"border-radius: 14;\n"
"}\n"
"QWidget#widget{\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0.0284091 rgba(129, 255, 251, 255), stop:0.9375 rgba(255, 255, 255, 255));\n"
"\n"
"border-radius: 14;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_widget.sizePolicy().hasHeightForWidth())
        self.button_widget.setSizePolicy(sizePolicy)
        self.button_widget.setMinimumSize(QtCore.QSize(64, 0))
        self.button_widget.setMaximumSize(QtCore.QSize(64, 16777215))
        self.button_widget.setObjectName("button_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.button_widget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_pushButton = QtWidgets.QPushButton(self.button_widget)
        self.main_pushButton.setMinimumSize(QtCore.QSize(40, 40))
        self.main_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.main_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/耳朵.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_pushButton.setIcon(icon1)
        self.main_pushButton.setObjectName("main_pushButton")
        self.verticalLayout.addWidget(self.main_pushButton)
        self.sound_recording_pushButton = QtWidgets.QPushButton(self.button_widget)
        self.sound_recording_pushButton.setMinimumSize(QtCore.QSize(40, 40))
        self.sound_recording_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.sound_recording_pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/录音.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sound_recording_pushButton.setIcon(icon2)
        self.sound_recording_pushButton.setObjectName("sound_recording_pushButton")
        self.verticalLayout.addWidget(self.sound_recording_pushButton)
        self.about_pushButton = QtWidgets.QPushButton(self.button_widget)
        self.about_pushButton.setMinimumSize(QtCore.QSize(40, 40))
        self.about_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.about_pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/305信息-圆框.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about_pushButton.setIcon(icon3)
        self.about_pushButton.setObjectName("about_pushButton")
        self.verticalLayout.addWidget(self.about_pushButton)
        self.help_pushButton = QtWidgets.QPushButton(self.button_widget)
        self.help_pushButton.setMinimumSize(QtCore.QSize(40, 40))
        self.help_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.help_pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/常见问题／相关问题2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_pushButton.setIcon(icon4)
        self.help_pushButton.setObjectName("help_pushButton")
        self.verticalLayout.addWidget(self.help_pushButton)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.min_pushButton = QtWidgets.QPushButton(self.button_widget)
        self.min_pushButton.setMinimumSize(QtCore.QSize(20, 20))
        self.min_pushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.min_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.min_pushButton.setText("")
        self.min_pushButton.setObjectName("min_pushButton")
        self.horizontalLayout.addWidget(self.min_pushButton)
        self.close_pushButton = QtWidgets.QPushButton(self.button_widget)
        self.close_pushButton.setMinimumSize(QtCore.QSize(20, 20))
        self.close_pushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.close_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_pushButton.setText("")
        self.close_pushButton.setObjectName("close_pushButton")
        self.horizontalLayout.addWidget(self.close_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addWidget(self.button_widget)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.verticalLayout_2.addLayout(self.main_layout)
        self.horizontalLayout_2.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "语音增强"))
from res import app_rc
